{
  "subject":"acct:ijustyn@masto.ai",
  "aliases":[
    "https://masto.ai/@ijustyn",
    "https://masto.ai/users/ijustyn"
  ],
  "links":[
    {
      "rel":"http://webfinger.net/rel/profile-page",
      "type":"text/html",
      "href":"https://masto.ai/@ijustyn"
    },
    {
      "rel":"self","type":"application/activity+json",
      "href":"https://masto.ai/users/ijustyn"
    },
    {
      "rel":"http://ostatus.org/schema/1.0/subscribe",
      "template":"https://masto.ai/authorize_interaction?uri={uri}"
    },
    {
      "rel":"http://webfinger.net/rel/avatar",
      "type":"image/png",
      "href":"https://s3.masto.ai/accounts/avatars/109/538/426/239/763/325/original/c5eb920ba7697cb7.png
    }
  ]
}